name: publish-to-npm
on: [push]
jobs:
  build-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '15.11'
      - run: npm install
      - run: npm outdated
